# Generated by Django 5.0 on 2023-12-05 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_image', models.ImageField(upload_to='media/category')),
                ('category_desc', models.TextField()),
                ('is_soft_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('locality', models.CharField(max_length=150)),
                ('landmark', models.CharField(max_length=150)),
                ('paddress', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('orginal_price', models.CharField()),
                ('offer_price', models.IntegerField()),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='media/product/img1')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='media/product/img2')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='media/product/img3')),
                ('product_image4', models.ImageField(blank=True, null=True, upload_to='media/product/img4')),
                ('product_image5', models.ImageField(blank=True, null=True, upload_to='media/product/img5')),
                ('quantity', models.IntegerField()),
                ('seating', models.CharField(blank=True, max_length=100, null=True)),
                ('colors', models.CharField(blank=True, max_length=100, null=True)),
                ('is_avialable', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is available')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='profile/profile.png', upload_to='profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
