# Generated by Django 5.0 on 2023-12-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/profile.png', null=True, upload_to='profile'),
        ),
    ]
