# Generated by Django 5.0 on 2024-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_products_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
