# Generated by Django 5.0 on 2023-12-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_order_shipping_remove_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
